const CONFIG={auctionUrl:'#',youthUrl:'#'};
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(el=>io.observe(el));
$('#menuBtn').onclick=()=>$('#mobileNav').classList.toggle('open');
$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('rc-theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('rc-theme')==='dark')document.body.classList.add('dark');
$('#searchForm').addEventListener('submit',e=>{e.preventDefault();const v=$('#searchInput').value.trim();toast(v?`“${v}” 검색 연결은 오픈 때 활성화됩니다.`:'검색어를 입력하세요.')});$$('[data-keyword]').forEach(b=>b.onclick=()=>{$('#searchInput').value=b.dataset.keyword;$('#searchInput').focus()});
$$('[data-tool]').forEach(a=>a.onclick=e=>{e.preventDefault();const url=CONFIG[a.dataset.tool+'Url'];url&&url!=='#'?location.href=url:toast('기존 계산기 주소를 app.js에 연결하면 바로 열립니다.')});
const modal=$('#modal');$$('[data-coming]').forEach(b=>b.onclick=()=>{$('#modalTitle').textContent=`${b.dataset.coming}는 준비 중입니다.`;modal.classList.add('open')});$$('[data-close]').forEach(x=>x.onclick=()=>modal.classList.remove('open'));
const numObs=new IntersectionObserver(es=>{if(!es[0].isIntersecting)return;$$('[data-count]').forEach(el=>{const end=+el.dataset.count,start=performance.now();function tick(t){const p=Math.min((t-start)/1000,1);el.textContent=Math.floor(end*(1-Math.pow(1-p,3))).toLocaleString()+(end>1000?'+':'');if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)});numObs.disconnect()},{threshold:.3});numObs.observe($('.numbers'));
