(() => {
  const toolLinks=[
    {id:'redevelopment',label:'재개발 계산기',path:'calc/',group:'청년·재개발'},
    {id:'youth-score',label:'청년주택 점수',path:'tools/youth-score/',group:'청년·재개발'},
    {id:'rent-check',label:'월세·전세 확인',path:'tools/rent-check/',group:'매매·전세'},
    {id:'apartment',label:'아파트 실거래',path:'tools/apartment/',group:'매매·전세'},
    {id:'jeonse-ratio',label:'전세가율 계산기',path:'tools/jeonse-ratio/',group:'매매·전세'},
    {id:'rent-vs-monthly',label:'전세 vs 월세 비교',path:'tools/rent-vs-monthly/',group:'매매·전세'},
    {id:'rent-conversion',label:'전월세 전환 계산기',path:'tools/rent-conversion/',group:'매매·전세'},
    {id:'rent-yield',label:'임대 수익률 계산기',path:'tools/rent-yield/',group:'매매·전세'},
    {id:'brokerage-fee',label:'중개보수 계산기',path:'tools/brokerage-fee/',group:'세금·비용'}
  ];
  const heroCopy={
    'redevelopment':{title:'재개발 자금 30초 계산기',desc:'소유주는 분담금, 매수자는 총투입금을 계산합니다.'},
    'youth-score':{title:'청년주택 점수 계산기',desc:'LH·SH 매입임대·청년안심주택 순위와 가점을 확인합니다.'},
    'rent-check':{title:'내 월세·전세, 적정한가요?',desc:'강서구 화곡동 실거래 기준으로 내 계약 조건을 비교합니다.'},
    'apartment':{title:'강서구 아파트 실거래',desc:'동과 단지를 골라 매매·전세·월세 실거래를 확인합니다.'},
    'jeonse-ratio':{title:'전세가율 계산기',desc:'매매가에서 전세보증금이 차지하는 비율을 확인합니다.'},
    'rent-vs-monthly':{title:'전세 vs 월세 비교',desc:'두 계약의 월 부담을 같은 기준으로 비교합니다.'},
    'rent-conversion':{title:'전월세 전환 계산기',desc:'보증금을 바꿀 때 월세가 얼마나 달라지는지 계산합니다.'},
    'rent-yield':{title:'임대 수익률 계산기',desc:'매매가·보증금·월세·대출 조건으로 실투자금과 세전 현금수익률을 계산합니다.'},
    'brokerage-fee':{title:'중개보수 계산기',desc:'매매·전세·월세의 최대 중개보수를 계산합니다.'}
  };
  const groups=['매매·전세','세금·비용','청년·재개발'];
  const join=(root,path)=>`${root}${path||''}`;
  const renderToolLink=(item,root,activeTool)=>`<a href="${join(root,item.path)}"${item.id===activeTool?' aria-current="page"':''}>${item.label}</a>`;
  const renderGroups=(root,activeTool)=>groups.map(group=>`<section class="v2-tool-footer__group"><strong>${group}</strong><div>${toolLinks.filter(x=>x.group===group).map(x=>renderToolLink(x,root,activeTool)).join('')}</div></section>`).join('');
  function ensureGA(){if(typeof window.gtag==='function')return;window.dataLayer=window.dataLayer||[];window.gtag=function(){window.dataLayer.push(arguments)};window.gtag('js',new Date());window.gtag('config','G-MPRR3J99YQ');if(!document.querySelector('script[src*="googletagmanager.com/gtag/js"]')){const s=document.createElement('script');s.async=true;s.src='https://www.googletagmanager.com/gtag/js?id=G-MPRR3J99YQ';document.head.appendChild(s)}}
  function brandText(value){return String(value||'').replace(/렌트체크\s*강서/gi,'Rent Check').replace(/Rent Check\s*강서/gi,'Rent Check')}
  function normalizeBrand(){document.title=brandText(document.title);document.querySelectorAll('meta[property="og:title"]').forEach(meta=>{meta.content=brandText(meta.content)});document.querySelectorAll('.brandbar').forEach(el=>{el.style.display='none'})}
  function ensureHeroRuntimeLock(){if(document.getElementById('v2-hero-runtime-lock'))return;const style=document.createElement('style');style.id='v2-hero-runtime-lock';style.textContent='html body.v2-tool-page .v2-normalized-hero>h1::after,html body.v2-tool-page .v2-normalized-hero>.v2-hero-description::after{content:none!important;display:none!important}html body.v2-tool-page .v2-normalized-hero>h1{font-size:28px!important;line-height:1.35!important;color:#fff!important;margin:0!important}html body.v2-tool-page .v2-normalized-hero>.v2-hero-description{display:block!important;font-size:14px!important;line-height:1.7!important;color:#d6dde6!important;margin:8px 0 0!important}@media(max-width:560px){html body.v2-tool-page .v2-normalized-hero>h1{font-size:23px!important}html body.v2-tool-page .v2-normalized-hero>.v2-hero-description{font-size:13px!important;line-height:1.65!important}}';document.head.appendChild(style)}
  function normalizeHero(body,activeTool){const copy=heroCopy[activeTool];if(!copy)return;const hero=body.querySelector('main .hero,main .chero,main .hd,.wrap>.hd,.wrap>header,.container>header');if(!hero)return;hero.classList.add('v2-normalized-hero');const brand=document.createElement('div');brand.className='v2-hero-brand';brand.textContent='Rent Check';const title=document.createElement('h1');title.textContent=copy.title;const desc=document.createElement('p');desc.className='v2-hero-description';desc.textContent=copy.desc;hero.replaceChildren(brand,title,desc);ensureHeroRuntimeLock()}
  function addDisclaimer(body,activeTool){if(activeTool==='calculator-notice'||document.querySelector('.v2-tool-disclaimer'))return;const main=body.querySelector('main,.wrap,.container');if(!main)return;const notice=document.createElement('p');notice.className='v2-tool-disclaimer';notice.textContent='계산 결과는 참고용입니다. 실제 적용 전 공식 기준을 확인하세요.';main.appendChild(notice)}
  function addResultNext(body,root){const results=[...body.querySelectorAll('.result,#result')];results.forEach(result=>{if(result.nextElementSibling?.classList?.contains('v2-result-next'))return;const row=document.createElement('nav');row.className='v2-result-next';row.setAttribute('aria-label','계산 후 이동');row.innerHTML=`<a href="${root}">홈으로</a><span>·</span><a href="${root}#calculators">다른 계산기</a>`;result.insertAdjacentElement('afterend',row);const sync=()=>{const cs=getComputedStyle(result);const visible=cs.display!=='none'&&cs.visibility!=='hidden'&&(result.classList.contains('show')||result.offsetHeight>0);row.classList.toggle('is-visible',visible)};new MutationObserver(sync).observe(result,{attributes:true,attributeFilter:['class','style']});sync()})}
  function fixAnalysisLinks(){document.querySelectorAll('a[href$="#article-library"]').forEach(a=>{if((a.textContent||'').includes('분석 글'))a.setAttribute('href','https://rent-check.kr/#article-library')})}
  function initializeToolShell(){const body=document.body;if(!body)return;const root=body.dataset.v2Root||'../../',activeTool=body.dataset.toolId||'';ensureGA();normalizeBrand();normalizeHero(body,activeTool);fixAnalysisLinks();if(!document.querySelector('.v2-toolbar')){const toolbar=document.createElement('header');toolbar.className='v2-toolbar';toolbar.innerHTML=`<div class="v2-toolbar__inner"><a class="v2-toolbar__home" href="${root}" aria-label="Rent Check 홈"><span class="v2-toolbar__mark" aria-hidden="true"><svg viewBox="0 0 28 28"><path d="M4 13 14 5l10 8v10H4z"></path><path d="m10 16 3 3 6-7"></path></svg></span><strong>Rent Check</strong></a><a class="v2-toolbar__tools" href="${root}#calculators">다른 도구 보기 <span aria-hidden="true">→</span></a></div>`;body.insertAdjacentElement('afterbegin',toolbar)}addDisclaimer(body,activeTool);addResultNext(body,root);if(!document.querySelector('.v2-tool-footer')){const footer=document.createElement('footer');footer.className='v2-tool-footer';footer.innerHTML=`<div class="v2-tool-footer__inner"><div class="v2-tool-footer__top"><a class="v2-tool-footer__brand" href="${root}" aria-label="Rent Check 홈"><span class="v2-tool-footer__mark" aria-hidden="true"><svg viewBox="0 0 28 28"><path d="M4 13 14 5l10 8v10H4z"></path><path d="m10 16 3 3 6-7"></path></svg></span><span><strong>Rent Check</strong><small>실거래로 더 정확하게</small></span></a><nav class="v2-tool-footer__actions" aria-label="공통 하단 바로가기"><a class="v2-tool-footer__home" href="${root}">홈으로</a><button class="v2-tool-footer__toggle" type="button" aria-expanded="false" aria-controls="v2-tool-footer-tools">다른 도구 보기 <span aria-hidden="true">⌄</span></button><a class="v2-tool-footer__notice" href="${join(root,'tools/calculator-notice/')}"${activeTool==='calculator-notice'?' aria-current="page"':''}>계산기 이용안내</a></nav></div><div class="v2-tool-footer__panel" id="v2-tool-footer-tools" hidden>${renderGroups(root,activeTool)}</div><div class="v2-tool-footer__legal"><a href="${join(root,'privacy.html')}">개인정보 처리방침</a></div></div>`;body.insertAdjacentElement('beforeend',footer);const toggle=footer.querySelector('.v2-tool-footer__toggle'),panel=footer.querySelector('.v2-tool-footer__panel');toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));panel.hidden=!open;toggle.classList.toggle('is-open',open);if(open)setTimeout(()=>panel.scrollIntoView({behavior:'smooth',block:'start'}),60)})}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initializeToolShell,{once:true});else initializeToolShell();
})();